<a href="https://colab.research.google.com/github/olive-green/data-science/blob/main/deep-learning/Tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


Task
1. ANN build
2. How to select hidden layers and neurons
3. Keras- Tuner (DL- Randomized search Cv)


In [3]:
x= tf.constant(42)

In [4]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
#we can change the type of constant
x=tf.constant(42,dtype='int64')

In [7]:
x

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [8]:
# we can create a numpy array
y=tf.constant([[4,3],[2,3]])

In [9]:
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [2, 3]], dtype=int32)>

In [10]:
# we can create a ones array using ones()
a= tf.ones(shape=(4,5))

In [11]:
a

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [12]:
# Zeros array
b=tf.zeros(shape=(4,5))

In [14]:
print(b)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32)


In [16]:
# we can add two numpy arrays as well
c=tf.add(a,b)

In [17]:
print(c)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(4, 5), dtype=float32)


In [18]:
# we can generate a random array of normal distribution
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.36891955, -0.02887177],
       [-0.5097932 ,  0.09667476]], dtype=float32)>

- Uniform Distribution

In [19]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 6],
       [7, 9]], dtype=int32)>

In [21]:
a= tf.Variable(23)

In [22]:
print(a)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>


In [23]:
tensor=tf.Variable([[[10.,11.,12.],[13.,14.,15.]],[[16.,17.,18.],[19.,20.,21.]]])

In [24]:
print(tensor.shape)

(2, 2, 3)


In [26]:
tensor1=tf.reshape(tensor,[2,6])

In [27]:
print(tensor1)

tf.Tensor(
[[10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21.]], shape=(2, 6), dtype=float32)


In [28]:
tensor1.numpy()

array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)