<a href="https://colab.research.google.com/github/olive-green/data-science/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy arrays are faster than lists in python
1. numpy arrays consists of homogenous elements

In [2]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(arr.ndim)

1


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
# we can also define type of data ie. how many of bits
arr=np.array([1,2,3,4,5],dtype="uint8")

uint8 - means unsigned int of 8 bits

In [ ]:
arr.dtype

dtype('uint8')

In [ ]:
# if you add any float value into int array then it converted into float
arr=np.array([1,2,3,4,5,6.6])

In [ ]:
arr.dtype

dtype('float64')

Numpy stands for numerical python
It is a library of python to work with Arrays

In [6]:
arr=np.array((1,23,4))

In [7]:
arr

array([ 1, 23,  4])

In [8]:
type(arr)

numpy.ndarray

In [21]:
arr1=np.ones(5)

In [22]:
arr1

array([1., 1., 1., 1., 1.])

In [23]:
arr1.dtype

dtype('float64')

In [25]:
arr1=np.ones(5,dtype="uint8")
arr1

array([1, 1, 1, 1, 1], dtype=uint8)

#2d arrays


In [29]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
arr=np.zeros((3,4),dtype="int")

In [34]:
print(arr.dtype)

int64


#np.arange

In [35]:
#it returns evenly spaced values within a given interval
arr=np.arange(1,10,2)

In [36]:
arr.shape

(5,)

In [37]:
arr.ndim

1

#Slicing

#Numpy arrays slicing is shallow copy ie. it returns a part of original array not create a other copy of it. 
1. While list's slicing is deep copy ie. it creates a copy 

In [39]:
arr=np.arange(2,30,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [42]:
arr1=arr[2:5]
arr1

array([ 6,  8, 10])

In [43]:
arr1[2]=55

In [44]:
print(arr1)

[ 6  8 55]


In [45]:
print(arr)

[ 2  4  6  8 55 12 14 16 18 20 22 24 26 28]


In [46]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[2::4]


array([3, 7])

In [55]:
#reverse an array
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#np.where
1. np.where(condition,clause(if its true) , clause(if its false))

In [58]:
arr=np.array([True,False,True,False,False])
arr

array([ True, False,  True, False, False])

In [59]:
np.where(arr,100,45)

array([100,  45, 100,  45,  45])

In [60]:
arr

array([ True, False,  True, False, False])

In [61]:
arr=np.arange(1,10)

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.where(arr>5,100,90) #jhan par 5 se badi values hongi whan 100 se replace kar dega and else 90

array([ 90,  90,  90,  90,  90, 100, 100, 100, 100])

#np.reshape

In [65]:
arr=np.zeros(20)

In [66]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [67]:
arr.ndim

1

In [68]:
arr.shape

(20,)

In [69]:
arr=arr.reshape(4,5)

In [70]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
arr.ndim

2